name: Deploy Contoso Chat

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/evaluations.yaml'
      - 'README.md'    

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8' # Minimum version supported by samples

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0

      - name: azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.OIDC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OIDC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OIDC_AZURE_SUBSCRIPTION_ID }}

      - name: Delegate azd authentication to azure-cli
        run: |
            azd config set auth.useAzCliAuth "true"

      - name: Set az account
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az account set --subscription ${{secrets.OIDC_AZURE_SUBSCRIPTION_ID}}

      - run: |
          pip install -r requirements.txt pytest

      - name: Deploy app
        run: azd up --no-prompt
        env:
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.OIDC_AZURE_SUBSCRIPTION_ID }}

      - name: Run tests
        run: pytest

